// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Test

#ifndef _TEST_UI_H
#define _TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_sec;
extern lv_obj_t * ui_Sensor_Panel1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Sensor_Panel2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Sensor_Panel3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Sensor_Panel5;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_547817801);    // assets\湿度.png
LV_IMG_DECLARE(ui_img_tvoc_png);    // assets\TVOC.png
LV_IMG_DECLARE(ui_img_394011210);    // assets\温度传感器 (1).png
LV_IMG_DECLARE(ui_img_1551580766);    // assets\二氧化碳.png
LV_IMG_DECLARE(ui_img_128x130_png);    // assets\128x130.png
LV_IMG_DECLARE(ui_img_arrow_right_16x16_png);    // assets\arrow_right_16X16.png
LV_IMG_DECLARE(ui_img_bg300_png);    // assets\bg300.png
LV_IMG_DECLARE(ui_img_btn_main_off_80x32_png);    // assets\btn_main_off_80x32.png
LV_IMG_DECLARE(ui_img_btn_main_on_80x32_png);    // assets\btn_main_on_80x32.png
LV_IMG_DECLARE(ui_img_button32x32_png);    // assets\button32x32.png
LV_IMG_DECLARE(ui_img_wifi_16x16_001_png);    // assets\wifi 16x16 001.png
LV_IMG_DECLARE(ui_img_wifi_128x160_png);    // assets\wifi_128x160.png
LV_IMG_DECLARE(ui_img_144205808);    // assets\圈40x40.png
LV_IMG_DECLARE(ui_img_1199486407);    // assets\温度02.png
LV_IMG_DECLARE(ui_img_162118600);    // assets\湿度传感器24.png
LV_IMG_DECLARE(ui_img_1208893048);    // assets\背景003.png
LV_IMG_DECLARE(ui_img_1530590678);    // assets\背景005.png
LV_IMG_DECLARE(ui_img_1574887283);    // assets\背景168x128.png
LV_IMG_DECLARE(ui_img_964567643);    // assets\菜单004.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
