// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Test

#ifndef _UI_COMP_USER_PANEL_H
#define _UI_COMP_USER_PANEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT User Panel
#define UI_COMP_USER_PANEL_USER_PANEL 0
#define UI_COMP_USER_PANEL_IMAGE2 1
#define UI_COMP_USER_PANEL_LABEL1 2
#define UI_COMP_USER_PANEL_IMAGE3 3
#define _UI_COMP_USER_PANEL_NUM 4
lv_obj_t * ui_User_Panel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
