// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Test

#include "../ui.h"


// COMPONENT light

lv_obj_t * ui_light_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_light;
    cui_light = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_light, 18);
    lv_obj_set_height(cui_light, 20);
    lv_obj_set_x(cui_light, 53);
    lv_obj_set_y(cui_light, 26);
    lv_obj_set_align(cui_light, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_light, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_light, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_light, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_light, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_light, lv_color_hex(0x6AAEFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_light, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_light, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_light, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(cui_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(cui_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(cui_light, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LIGHT_NUM);
    children[UI_COMP_LIGHT_LIGHT] = cui_light;
    lv_obj_add_event_cb(cui_light, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_light, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_light_create_hook(cui_light);
    return cui_light;
}

