// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Test

#include "../ui.h"


// COMPONENT Panel1

lv_obj_t * ui_Panel1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel1;
    cui_Panel1 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel1, 100);
    lv_obj_set_height(cui_Panel1, 50);
    lv_obj_set_x(cui_Panel1, 0);
    lv_obj_set_y(cui_Panel1, -43);
    lv_obj_set_align(cui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image1;
    cui_Image1 = lv_img_create(cui_Panel1);
    lv_img_set_src(cui_Image1, &ui_img_394011210);
    lv_obj_set_width(cui_Image1, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(cui_Image1, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(cui_Image1, -30);
    lv_obj_set_y(cui_Image1, 0);
    lv_obj_set_align(cui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_Panel1);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label1, 10);
    lv_obj_set_y(cui_Label1, 0);
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label1, "0  C");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL1_NUM);
    children[UI_COMP_PANEL1_PANEL1] = cui_Panel1;
    children[UI_COMP_PANEL1_IMAGE1] = cui_Image1;
    children[UI_COMP_PANEL1_LABEL1] = cui_Label1;
    lv_obj_add_event_cb(cui_Panel1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel1_create_hook(cui_Panel1);
    return cui_Panel1;
}

