// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Test

#ifndef _UI_COMP_NAVIGATION_BAR_H
#define _UI_COMP_NAVIGATION_BAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Navigation Bar
#define UI_COMP_NAVIGATION_BAR_NAVIGATION_BAR 0
#define UI_COMP_NAVIGATION_BAR_LIGHT_TO_MENU 1
#define UI_COMP_NAVIGATION_BAR_LIGHT_TO_RETURN 2
#define UI_COMP_NAVIGATION_BAR_RETURN_IMAGE 3
#define UI_COMP_NAVIGATION_BAR_MENU_IMAGE 4
#define _UI_COMP_NAVIGATION_BAR_NUM 5
lv_obj_t * ui_Navigation_Bar_create(lv_obj_t * comp_parent);
void ui_event_comp_Navigation_Bar_Return_Image(lv_event_t * e);
void ui_event_comp_Navigation_Bar_Menu_Image(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
