// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Test

#include "../ui.h"


void ui_event_comp_Navigation_Bar_Return_Image(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_Navigation_Bar = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        OpaOn_Animation(comp_Navigation_Bar[UI_COMP_NAVIGATION_BAR_LIGHT_TO_RETURN], 0);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        OpaOff_Animation(comp_Navigation_Bar[UI_COMP_NAVIGATION_BAR_LIGHT_TO_RETURN], 0);
    }
}
void ui_event_comp_Navigation_Bar_Menu_Image(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_Navigation_Bar = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        OpaOff_Animation(comp_Navigation_Bar[UI_COMP_NAVIGATION_BAR_LIGHT_TO_MENU], 0);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        OpaOn_Animation(comp_Navigation_Bar[UI_COMP_NAVIGATION_BAR_LIGHT_TO_MENU], 0);
    }
}

// COMPONENT Navigation Bar

lv_obj_t * ui_Navigation_Bar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Navigation_Bar;
    cui_Navigation_Bar = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Navigation_Bar, 128);
    lv_obj_set_height(cui_Navigation_Bar, 16);
    lv_obj_set_x(cui_Navigation_Bar, 0);
    lv_obj_set_y(cui_Navigation_Bar, 65);
    lv_obj_set_align(cui_Navigation_Bar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Navigation_Bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Navigation_Bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Navigation_Bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Navigation_Bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Navigation_Bar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Light_To_Menu;
    cui_Light_To_Menu = ui_light_create(cui_Navigation_Bar);
    lv_obj_set_x(cui_Light_To_Menu, 52);
    lv_obj_set_y(cui_Light_To_Menu, 26);

    lv_obj_t * cui_Light_To_Return;
    cui_Light_To_Return = ui_light_create(cui_Navigation_Bar);
    lv_obj_set_x(cui_Light_To_Return, -52);
    lv_obj_set_y(cui_Light_To_Return, 26);

    lv_obj_t * cui_Return_Image;
    cui_Return_Image = lv_img_create(cui_Navigation_Bar);
    lv_obj_set_width(cui_Return_Image, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(cui_Return_Image, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(cui_Return_Image, -47);
    lv_obj_set_y(cui_Return_Image, 0);
    lv_obj_set_align(cui_Return_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Return_Image, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE |
                    LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Return_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Menu_Image;
    cui_Menu_Image = lv_img_create(cui_Navigation_Bar);
    lv_img_set_src(cui_Menu_Image, &ui_img_964567643);
    lv_obj_set_width(cui_Menu_Image, LV_SIZE_CONTENT);   /// -8
    lv_obj_set_height(cui_Menu_Image, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(cui_Menu_Image, 47);
    lv_obj_set_y(cui_Menu_Image, 0);
    lv_obj_set_align(cui_Menu_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Menu_Image, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Menu_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_NAVIGATION_BAR_NUM);
    children[UI_COMP_NAVIGATION_BAR_NAVIGATION_BAR] = cui_Navigation_Bar;
    children[UI_COMP_NAVIGATION_BAR_LIGHT_TO_MENU] = cui_Light_To_Menu;
    children[UI_COMP_NAVIGATION_BAR_LIGHT_TO_RETURN] = cui_Light_To_Return;
    children[UI_COMP_NAVIGATION_BAR_RETURN_IMAGE] = cui_Return_Image;
    children[UI_COMP_NAVIGATION_BAR_MENU_IMAGE] = cui_Menu_Image;
    lv_obj_add_event_cb(cui_Navigation_Bar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Navigation_Bar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Return_Image, ui_event_comp_Navigation_Bar_Return_Image, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Menu_Image, ui_event_comp_Navigation_Bar_Menu_Image, LV_EVENT_ALL, children);
    ui_comp_Navigation_Bar_create_hook(cui_Navigation_Bar);
    return cui_Navigation_Bar;
}

