// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Test

#include "../ui.h"


// COMPONENT Sensor Panel

lv_obj_t * ui_Sensor_Panel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Sensor_Panel;
    cui_Sensor_Panel = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Sensor_Panel, 63);
    lv_obj_set_height(cui_Sensor_Panel, 28);
    lv_obj_set_x(cui_Sensor_Panel, -32);
    lv_obj_set_y(cui_Sensor_Panel, -6);
    lv_obj_set_align(cui_Sensor_Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Sensor_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Sensor_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Sensor_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Sensor_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_Sensor_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image1;
    cui_Image1 = lv_img_create(cui_Sensor_Panel);
    lv_img_set_src(cui_Image1, &ui_img_394011210);
    lv_obj_set_width(cui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image1, -19);
    lv_obj_set_y(cui_Image1, 0);
    lv_obj_set_align(cui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label6;
    cui_Label6 = lv_label_create(cui_Sensor_Panel);
    lv_obj_set_width(cui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label6, 14);
    lv_obj_set_y(cui_Label6, 0);
    lv_obj_set_align(cui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label6, "45 C");
    lv_obj_set_style_text_color(cui_Label6, lv_color_hex(0x4F42D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SENSOR_PANEL_NUM);
    children[UI_COMP_SENSOR_PANEL_SENSOR_PANEL] = cui_Sensor_Panel;
    children[UI_COMP_SENSOR_PANEL_IMAGE1] = cui_Image1;
    children[UI_COMP_SENSOR_PANEL_LABEL6] = cui_Label6;
    lv_obj_add_event_cb(cui_Sensor_Panel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Sensor_Panel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Sensor_Panel_create_hook(cui_Sensor_Panel);
    return cui_Sensor_Panel;
}

