// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Test

#include "../ui.h"


// COMPONENT User Panel

lv_obj_t * ui_User_Panel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_User_Panel;
    cui_User_Panel = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_User_Panel, 128);
    lv_obj_set_height(cui_User_Panel, 24);
    lv_obj_set_x(cui_User_Panel, 0);
    lv_obj_set_y(cui_User_Panel, 5);
    lv_obj_set_align(cui_User_Panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_User_Panel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_User_Panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_User_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_User_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_User_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_User_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_User_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_User_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_User_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_User_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_User_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_User_Panel, lv_color_hex(0x84ACFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(cui_User_Panel, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(cui_User_Panel, 10, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(cui_User_Panel, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_x(cui_User_Panel, 0, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_ofs_y(cui_User_Panel, 0, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_t * cui_Image2;
    cui_Image2 = lv_img_create(cui_User_Panel);
    lv_obj_set_width(cui_Image2, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(cui_Image2, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(cui_Image2, -47);
    lv_obj_set_y(cui_Image2, -1);
    lv_obj_set_align(cui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_User_Panel);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label1, "User");

    lv_obj_t * cui_Image3;
    cui_Image3 = lv_img_create(cui_User_Panel);
    lv_img_set_src(cui_Image3, &ui_img_arrow_right_16x16_png);
    lv_obj_set_width(cui_Image3, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(cui_Image3, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(cui_Image3, 40);
    lv_obj_set_y(cui_Image3, 0);
    lv_obj_set_align(cui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image3, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(cui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_USER_PANEL_NUM);
    children[UI_COMP_USER_PANEL_USER_PANEL] = cui_User_Panel;
    children[UI_COMP_USER_PANEL_IMAGE2] = cui_Image2;
    children[UI_COMP_USER_PANEL_LABEL1] = cui_Label1;
    children[UI_COMP_USER_PANEL_IMAGE3] = cui_Image3;
    lv_obj_add_event_cb(cui_User_Panel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_User_Panel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_User_Panel_create_hook(cui_User_Panel);
    return cui_User_Panel;
}

