// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Test

#ifndef _TEST_UI_COMP_HOOK_H
#define _TEST_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_light_create_hook(lv_obj_t * comp);
void ui_comp_Navigation_Bar_create_hook(lv_obj_t * comp);
void ui_comp_Panel1_create_hook(lv_obj_t * comp);
void ui_comp_Sensor_Panel_create_hook(lv_obj_t * comp);
void ui_comp_User_Panel_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
