// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Test

#ifndef _UI_COMP_LIGHT_H
#define _UI_COMP_LIGHT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT light
#define UI_COMP_LIGHT_LIGHT 0
#define _UI_COMP_LIGHT_NUM 1
lv_obj_t * ui_light_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
